package grub

import (
	"strings"
	"testing"
)

func TestParseGrubenv(t *testing.T) {
	const realAL2023 = `# GRUB Environment Block
# WARNING: Do not edit this file by tools other than grub-editenv!!!
boot_success=0
saved_entry=ec22ff19161cb00ddacaddc223f52185-6.1.141-167.250.amzn2023.aarch64
boot_indeterminate=0
######################################`
	tests := []struct {
		name  string
		input string
		key   string
		want  string
	}{
		{
			name:  "saved_entry from real AL2023 grubenv",
			input: realAL2023,
			key:   "saved_entry",
			want:  "ec22ff19161cb00ddacaddc223f52185-6.1.141-167.250.amzn2023.aarch64",
		},
		{
			name:  "boot_success",
			input: realAL2023,
			key:   "boot_success",
			want:  "0",
		},
		{
			name:  "missing key returns empty",
			input: realAL2023,
			key:   "next_entry",
			want:  "",
		},
		{
			name:  "empty input",
			input: "",
			key:   "saved_entry",
			want:  "",
		},
		{
			name:  "comment lines ignored",
			input: "# saved_entry=should-be-ignored\nsaved_entry=actual\n",
			key:   "saved_entry",
			want:  "actual",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ParseGrubenv(strings.NewReader(tt.input), tt.key)
			if got != tt.want {
				t.Errorf("ParseGrubenv() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestParseBLSVersion(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{
			name: "version field takes precedence (AL2023 BLS entry)",
			input: strings.Join([]string{
				"title Amazon Linux (6.1.141-167.250.amzn2023.aarch64)",
				"version 6.1.141-167.250.amzn2023.aarch64",
				"linux /boot/vmlinuz-6.1.141-167.250.amzn2023.aarch64",
				"initrd /boot/initramfs-6.1.141-167.250.amzn2023.aarch64.img $tuned_initrd",
				"options root=UUID=... ro",
				"id amzn-20250409-6.1.141-167.250.amzn2023.aarch64",
				"grub_users $grub_users",
				"grub_arg --unrestricted",
				"grub_class amzn",
				"",
			}, "\n"),
			want: "6.1.141-167.250.amzn2023.aarch64",
		},
		{
			name: "fallback to linux line when version missing",
			input: strings.Join([]string{
				"title Some Entry",
				"linux /boot/vmlinuz-6.5.6-300.fc39.x86_64",
				"options root=...",
				"",
			}, "\n"),
			want: "6.5.6-300.fc39.x86_64",
		},
		{
			name: "tab-separated key/value",
			input: strings.Join([]string{
				"title\tAL2023",
				"version\t6.1.141-167.250.amzn2023.aarch64",
				"",
			}, "\n"),
			want: "6.1.141-167.250.amzn2023.aarch64",
		},
		{
			name:  "no kernel info present",
			input: "title Some Entry\noptions root=...\n",
			want:  "",
		},
		{
			name:  "empty",
			input: "",
			want:  "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ParseBLSVersion(strings.NewReader(tt.input))
			if got != tt.want {
				t.Errorf("ParseBLSVersion() = %q, want %q", got, tt.want)
			}
		})
	}
}
