package grub

import (
	"context"
	"testing"
	"testing/fstest"

	"github.com/aquasecurity/trivy/pkg/fanal/analyzer"
)

func TestPostAnalyze(t *testing.T) {
	a := &kernelGRUBAnalyzer{}
	ctx := context.Background()

	// Real-world Amazon Linux 2023 grubenv content (1KB block, padding
	// truncated). saved_entry references the BLS entry filename.
	const al2023Grubenv = `# GRUB Environment Block
# WARNING: Do not edit this file by tools other than grub-editenv!!!
boot_success=1
saved_entry=ec22ff19161cb00ddacaddc223f52185-6.1.141-167.250.amzn2023.aarch64
boot_indeterminate=0
`
	const al2023BLSEntry = `title Amazon Linux (6.1.141-167.250.amzn2023.aarch64)
version 6.1.141-167.250.amzn2023.aarch64
linux /boot/vmlinuz-6.1.141-167.250.amzn2023.aarch64
initrd /boot/initramfs-6.1.141-167.250.amzn2023.aarch64.img
options root=UUID=... ro
`

	tests := []struct {
		name string
		fs   fstest.MapFS
		want string
	}{
		{
			name: "AL2023 grubenv → BLS entry → version (running kernel)",
			fs: fstest.MapFS{
				"boot/grub2/grubenv": &fstest.MapFile{Data: []byte(al2023Grubenv)},
				"boot/loader/entries/ec22ff19161cb00ddacaddc223f52185-6.1.141-167.250.amzn2023.aarch64.conf": &fstest.MapFile{
					Data: []byte(al2023BLSEntry),
				},
				// A second entry for a different kernel must be ignored
				// because saved_entry only points to the running one.
				"boot/loader/entries/23681ec6a57c485699714c1ae1da1309-6.1.166-197.305.amzn2023.aarch64.conf": &fstest.MapFile{
					Data: []byte("title Amazon Linux\nversion 6.1.166-197.305.amzn2023.aarch64\n"),
				},
			},
			want: "6.1.141-167.250.amzn2023.aarch64",
		},
		{
			name: "legacy /boot/grub/grubenv path",
			fs: fstest.MapFS{
				"boot/grub/grubenv": &fstest.MapFile{Data: []byte("saved_entry=foo-5.15.0-92-generic\n")},
				"boot/loader/entries/foo-5.15.0-92-generic.conf": &fstest.MapFile{
					Data: []byte("version 5.15.0-92-generic\n"),
				},
			},
			want: "5.15.0-92-generic",
		},
		{
			name: "grubenv missing → no detection",
			fs: fstest.MapFS{
				"boot/loader/entries/foo-1.2.3.conf": &fstest.MapFile{Data: []byte("version 1.2.3\n")},
			},
			want: "",
		},
		{
			name: "grubenv has no saved_entry",
			fs: fstest.MapFS{
				"boot/grub2/grubenv": &fstest.MapFile{Data: []byte("boot_success=1\n")},
			},
			want: "",
		},
		{
			name: "saved_entry refers to missing BLS file",
			fs: fstest.MapFS{
				"boot/grub2/grubenv": &fstest.MapFile{Data: []byte("saved_entry=ghost-9.9.9\n")},
			},
			want: "",
		},
		{
			name: "BLS entry has no version or linux line",
			fs: fstest.MapFS{
				"boot/grub2/grubenv": &fstest.MapFile{Data: []byte("saved_entry=foo-1.2.3\n")},
				"boot/loader/entries/foo-1.2.3.conf": &fstest.MapFile{
					Data: []byte("title Some entry\noptions root=...\n"),
				},
			},
			want: "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			res, err := a.PostAnalyze(ctx, analyzer.PostAnalysisInput{FS: tt.fs})
			if err != nil {
				t.Fatalf("PostAnalyze() error = %v", err)
			}
			got := ""
			if res != nil {
				got = res.RunningKernelRelease
			}
			if got != tt.want {
				t.Errorf("RunningKernelRelease = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestRequired(t *testing.T) {
	a := &kernelGRUBAnalyzer{}
	yes := []string{
		"boot/grub2/grubenv",
		"boot/grub/grubenv",
		"boot/loader/entries/foo-1.2.3.conf",
		"boot/loader/entries/ec22ff19161cb00ddacaddc223f52185-6.1.141-167.250.amzn2023.aarch64.conf",
	}
	for _, p := range yes {
		if !a.Required(p, nil) {
			t.Errorf("Required(%q) = false, want true", p)
		}
	}
	no := []string{
		"boot/grub2/grub.cfg",
		"boot/loader/entries/subdir/nested.conf",
		"boot/loader/entries/README",
		"etc/default/grub",
		"var/log/dmesg",
		"var/log/journal/abc/system.journal",
	}
	for _, p := range no {
		if a.Required(p, nil) {
			t.Errorf("Required(%q) = true, want false", p)
		}
	}
}
